# Site settings
title: RSE

url: http://rsemeeting.github.io/
baseurl: ''

# RSE data
organizer-email : rsemeeting@gmail.com
copyright: Conference Organizers
conference_title: "Robotics Software Engineering"
conference_title_short: "RSE"

# Current meeting
year: "2024"
dates: September X-Y
venue: University of Bremen, Germany

# Color settings
color:
  primary-dark: '#9d2246'
  title: '#ebf0f4'
  links: '#0068b4'
  accent: '#d50c2f'



# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed